package net.yefremov.sample.codegen

import java.io.{PrintWriter, FileWriter, File}

/**
 * Represents a class generated by a generator.
 * @param file where should the file be saved
 * @param content content of the file
 */
case class GeneratedClass(file: File, content: String) {



}
